services:
  x86_64:
    image: openwrtorg/sdk:x86_64-openwrt-22.03
    volumes:
      - .:/home/build/openwrt/QiuSimons/mosdns
      - ./bin:/home/build/openwrt/bin
      - ./build.sh:/home/build/openwrt/build.sh
    command: /home/build/openwrt/build.sh
  aarch64:
    image: openwrtorg/sdk:aarch64_generic-22.03.3
    volumes:
      - .:/home/build/openwrt/QiuSimons/mosdns
      - ./bin:/home/build/openwrt/bin
      - ./build.sh:/home/build/openwrt/build.sh
    command: /home/build/openwrt/build.sh
      